testing:
  stage: test
  script:
    - sudo mkdir -p /galaxy
    - |
      docker run -v /var/run/docker.sock:/var/run/docker.sock \
                 -v `pwd`:`pwd` \
                 --workdir `pwd`/tools/neutrons \
                 -v /tmp:/tmp \
                 code.ornl.gov:4567/ndip/galaxy-tools /bin/bash -c "
        git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep 'tools/neutrons/.*\.xml$' > changed_tools.txt
        if [ -s changed_tools.txt ]; then
          while IFS= read -r tool; do
            tool_path=`pwd`/tools/neutrons/\$tool
            if [ -f \$tool_path ]; then
              planemo test --galaxy_root /galaxy --docker --no_conda_auto_init --test_output junit_output.xml \$tool_path
            else
              echo \"Tool definition file \$tool_path does not exist.\"
            fi
          done < changed_tools.txt
        else
          echo 'No tool definition changes detected.'
        fi
      "
  artifacts:
    when: always
    paths:
      - tools/neutrons/junit_output.xml
  tags:
    - rse-multi-builder
  only:
    changes:
      - tools/neutrons/**/*.xml
