stages:
  - build
  - test

variables:
  GIT_STRATEGY: clone
  CONTAINER_URL: "${NDIP_DOCKER_REPOSITORY}/${CI_PROJECT_PATH}"

# This import is for the func_rse_docker_* functions
before_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - docker login -u $NDIP_DOCKER_USER -p $NDIP_DOCKER_PASSWORD $NDIP_DOCKER_REPOSITORY
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup

after_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup
  - sudo chown -R gitlab-runner .

service-build:
  stage: build
  script:
    - >    
      docker build
      -f dockerfiles/Dockerfile 
      -t galaxy_tools .
    - docker tag galaxy_tools $CONTAINER_URL:build-$CI_COMMIT_SHORT_SHA
    - docker tag galaxy_tools $CONTAINER_URL:latest
    - docker push $CONTAINER_URL:latest
    - docker push $CONTAINER_URL:build-$CI_COMMIT_SHORT_SHA
  when: manual
  tags:
    - rse-multi-builder

testing:
  stage: test
  variables:
    ENVIRONMENT: "calvera-test"
  script:
    - echo "Running tests for all tools."
    - cd `pwd`/tools/neutrons
    - TEST_FOLDERS=`find . -type d -name retired -prune -o -type d -name dockerfiles -prune -o -type f -name "*.xml" -exec grep -l "<test>" {} + | awk -F/ 'BEGIN { OFS="/"; } { $NF=""; sub(/\/$/, ""); print }' | sort -u | sed 's/^\.\///'`
    - echo testing in $TEST_FOLDERS
    - ERROR=0
    - |
      for FOLDER in $TEST_FOLDERS
      do
        docker run -v `pwd`:`pwd` --workdir `pwd`/$FOLDER  $CONTAINER_URL \
          planemo test --galaxy_root /galaxy --docker --no_conda_auto_init \
          --test_output_json `pwd`/test_output_${FOLDER}.json \
          --test_output_junit `pwd`/test_output_${FOLDER}.xml \
          --galaxy_url https://calvera-test.ornl.gov \
          --galaxy_user_key $CALVERA_TEST_API_KEY \
          --galaxy_admin_key $CALVERA_TEST_ADMIN_KEY || ERROR=1
      done
    - cd -
    - if [ "$CI_PIPELINE_SOURCE" = "schedule" ] || [ "$CI_PIPELINE_SOURCE" = "web" ]; then
      docker run -v `pwd`:`pwd` --workdir `pwd` -e PROMETHEUS_URL -e ENVIRONMENT $CONTAINER_URL python3 scripts/push_to_gateway.py tools/neutrons
      fi
    - exit $ERROR
  artifacts:
    when: always
    reports:
      junit: tools/neutrons/test_output*.xml
  tags:
    - rse-multi-builder
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        ENVIRONMENT: "calvera"
      when: manual
    - when: manual
