FROM --platform=amd64 regproxy.ornl.gov/hub_proxy/python:3.10-slim AS source

RUN apt update && apt install

RUN pip install nova-galaxy

COPY . /src
WORKDIR /src

CMD python tests/interactive_tools.py