FROM regproxy.ornl.gov/hub_proxy/ubuntu:noble


COPY . /opt/run
WORKDIR /opt/run

RUN curl -fsSL https://pixi.sh/install.sh | sh
ENV PATH="/root/.pixi/bin:${PATH}"
RUN pixi install
SHELL [ "pixi", "run" ]
ENTRYPOINT [ "pixi", "run" ]

RUN chmod og+rwX -R /opt/run