# Generated by Claude Code using Sonnet 5 on August 26th, 2026.

import re
import sys
import xml.etree.ElementTree as ET

# planemo embeds the raw failure text (Python tracebacks, JSON payloads) into
# a `message="..."` attribute without XML-escaping it, so a traceback like
# `File "foo.py"` or `in <lambda>` breaks the attribute's quoting and the
# whole report fails to parse. The literal `"><![CDATA[` that always follows
# the message attribute is a reliable anchor for where it actually ends.
FAILURE_MESSAGE = re.compile(
    r'(<(?:failure|error) message=")(.*?)("><!\[CDATA\[)',
    re.DOTALL,
)


def _escape_attribute_value(value):
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _repair(xml_text):
    return FAILURE_MESSAGE.sub(
        lambda m: m.group(1) + _escape_attribute_value(m.group(2)) + m.group(3),
        xml_text,
    )


def fix_junit_xml(path):
    with open(path, "r", encoding="utf-8") as handle:
        original = handle.read()

    try:
        ET.fromstring(original)
        return
    except ET.ParseError:
        pass

    repaired = _repair(original)

    try:
        ET.fromstring(repaired)
    except ET.ParseError as exc:
        print(f"Could not repair {path}, leaving it as-is: {exc}", file=sys.stderr)
        return

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(repaired)
    print(f"Repaired malformed JUnit XML: {path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python fix_junit_xml.py <junit.xml> [<junit.xml> ...]")
        sys.exit(1)

    for xml_path in sys.argv[1:]:
        fix_junit_xml(xml_path)
